### ISSUE TITLE
Make CopyLayer documentation indicate it can be used for queries

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-geoprocessor-python-doc-user#9]
### Content Suggestion ###

The CopyGeoLayer documentation, including the sentence in the overview page, does not emphasize enough the power of doing filter/queries to copy a subset of a GeoLayer.  This needs to be more obvious so that people know to use this command.  For example, the summary could be:  "copy a GeoLayer, optionally constraining the copy to a subset of the original features"

**Comment by egiles16** [comment]
Updated the CopyGeoLayer command user documentation to emphasize its querying capabilities. Updated the command-ref overview page to reflect the commands extended capabilities.
